swagger: "2.0"
info:
  description: "This is the API of CICBO - CICBO is a Corona Business Optimizer. \nBy Deborah Djon and Ferdinand Koenig for Web Engineering 2 at Cooperative State University Stuttgart (DHBW Stuttgart) \nLecturer: Danny Amor (DXC)"
  version: "1.1"
  title: "CICBO"
  termsOfService: "https://github.com/lipilli/CICBO"
  contact:
    email: "inf19211@lehre.dhbw-stuttgart.de"
  license:
    name: "Non defined license"
    url: "https://github.com/lipilli/CICBO"
host: "localhost"
basePath: "/"
tags:
- name: "guest"
  description: "Managing your digital guest list"
- name: "staff"
  description: "Access to your staff"
- name: "room"
  description: "Operations on different rooms"
- name: "alarm"
  description: "All meta-methods in case of an outbreak"
schemes:
- "https"
- "http"

paths:
  /guest:
    post:
      tags:
      - "guest"
      summary: "Add a new guest"
      description: ""
      operationId: "addGuest"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "guest"
        description: "Guest object that needs to be added to the guest list"
        required: true
        schema:
          $ref: "#/definitions/Guest"
      responses:
        "200":
          description: "Everything OK"
        "405":
          description: "Invalid input"
        "418":
          description: "I'm a teapot and not a valid room. (No existing room with this number)"

    get:
      tags:
      - "guest"
      summary: "List all guests"
      description: ""
      operationId: "listGuests"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Everything OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GuestwId"
      
  /guest/find:
    get:
      tags:
      - "guest"
      summary: "Finds guests"
      description: ""
      operationId: "findGuests"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Search filter"
        description: "Search filter object"
        required: true
        schema:
          $ref: '#/definitions/SearchObject'
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/GuestwId"
        "400":
          description: "Invalid status value"

  /guest/{guestId}:
    get:
      tags:
      - "guest"
      summary: "Find guest by ID"
      description: "Returns a single guest"
      operationId: "getGuestById"
      produces:
      - "application/json"
      parameters:
      - name: "guestId"
        in: "path"
        description: "ID of guest to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GuestwId"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Guest not found"

    put:
      tags:
      - "guest"
      summary: "Updates a guest with form data"
      description: ""
      operationId: "updateGuestWithForm"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "guestId"
        in: "path"
        description: "guest id to update"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "guest"
        description: "Updated guest"
        required: true
        schema:
          $ref: "#/definitions/Guest"
      responses:
        "405":
          description: "Invalid input"

    delete:
      tags:
      - "guest"
      summary: "Deletes a guest"
      description: ""
      operationId: "deleteGuest"
      parameters:
      - name: "guestId"
        in: "path"
        description: "guest id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Deleted guest"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Guest not found"
        
  /staff:
    post:
      tags:
      - "staff"
      summary: "Add a new staff member"
      description: ""
      operationId: "addStaff"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "staff"
        description: "Staff object that needs to be added to the staff list"
        required: true
        schema:
          $ref: "#/definitions/Staff"
      responses:
        "200":
          description: "Everything OK"
        "405":
          description: "Invalid input"
        "418":
          description: "I'm a teapot and not a valid room. (No existing room with this number)"
    get:
      tags:
      - "staff"
      summary: "List all staff members"
      description: ""
      operationId: "listStaff"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Everything OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/StaffwId"
      
  /staff/find:
    get:
      tags:
      - "staff"
      summary: "Finds staff members"
      description: ""
      operationId: "findStaffMembers"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Search filter"
        description: "Search filter object"
        required: true
        schema:
          $ref: '#/definitions/SearchObject'
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/StaffwId"
        "400":
          description: "Invalid status value"
  /staff/{staffId}:
    get:
      tags:
      - "staff"
      summary: "Find staff member by ID"
      description: "Returns a single staff member"
      operationId: "getStaffMemberById"
      produces:
      - "application/json"
      parameters:
      - name: "staffId"
        in: "path"
        description: "ID of staff member to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/StaffwId"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Staff member not found"
    put:
      tags:
      - "staff"
      summary: "Updates a staff member"
      description: ""
      operationId: "updateStaff"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "staffId"
        in: "path"
        description: "staff id to update"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "staff"
        description: "Updated staff"
        required: true
        schema:
          $ref: "#/definitions/Staff"
      responses:
        "405":
          description: "Invalid input"
    delete:
      tags:
      - "staff"
      summary: "Deletes a staff member"
      description: ""
      operationId: "deleteStaffMember"
      parameters:
      - name: "staffId"
        in: "path"
        description: "staff id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Deleted staff member"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Staff member not found"
        
  /room:
    post:
      tags:
      - "room"
      summary: "Add a new room"
      description: ""
      operationId: "addRoom"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "room"
        description: "Room object that needs to be added to the room list"
        required: true
        schema:
          $ref: "#/definitions/Room"
      responses:
        "405":
          description: "Invalid input"
    get:
      tags:
      - "room"
      summary: "List all rooms"
      description: ""
      operationId: "listRooms"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Everything OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Room"
  
  /room/{roomNr}:       
    delete:
      tags:
      - "room"
      summary: "Deletes a room"
      description: "Deletes a room if not in use. If it is in use, it sets the active-flag to false. \nIn a later version, this could be extended to automatically deleting inactive rooms if they are not in use"
      operationId: "deleteRoom"
      parameters:
      - name: "roomNr"
        in: "path"
        description: "room number to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "Deleted room"
        "202":
          description: "Set active-flag to false"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Room not found"
          
  /alarm:
    get:
      tags:
      - "alarm"
      summary: "Creates contact list with potential contaminated persons"
      description: ""
      operationId: "createContactList"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "Search filter"
        description: "Alarm query object"
        required: true
        schema:
          $ref: "#/definitions/AlarmQueryObject"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ContactList"
        "400":
          description: "Invalid status value"
        
        

definitions:
  Room:
      type: "object"
      required:
      - "number"
      properties:
          number:
              type: "integer"
          name:
              type: "string"
              example: "large hall"
          active:
              type: "boolean"
  RoomIdentifier:
      type: "object"
      required:
      - "number"
      properties:
          number:
              type: "integer"
  StaffwId:
    type: "object"
    description: "Staff-object in response"
    required:
    - "id"
    - "name"
    - "firstName"
    - "arrivedAt"
    - "leftAt"
    - "room"
    properties:
        id:
            type: "integer"
            format: "int64"
        firstName:
            type: "string"
            example: "Jane"
        name:
            type: "string"
            example: "Doe"
        mail:
            type: "string"
            pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
            example: "jane.doe@example.com"
        phone:
            type: "string"
        adress:
            type: "string"
        arrivedAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        leftAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        rooms:
            type: "array"
            items:
              $ref: "#/definitions/Room"
  Staff:
    type: "object"
    description: "Staff-object in querry"
    required:
    - "name"
    - "firstName"
    - "arrivedAt"
    - "leftAt"
    - "room"
    properties:
        firstName:
            type: "string"
            example: "Jane"
        name:
            type: "string"
            example: "Doe"
        mail:
            type: "string"
            pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
            example: "jane.doe@example.com"
        phone:
            type: "string"
        adress:
            type: "string"
        arrivedAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        leftAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        rooms:
            type: "array"
            items:
              $ref: "#/definitions/RoomIdentifier"
  GuestwId:
    type: "object"
    description: "Guest-object in response"
    required:
    - "id"
    - "name"
    - "firstName"
    - "arrivedAt"
    - "leftAt"
    - "room"
    properties:
        id:
            type: "integer"
            format: "int64"
        firstName:
            type: "string"
            example: "Jane"
        name:
            type: "string"
            example: "Doe"
        mail:
            type: "string"
            pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
            example: "jane.doe@example.com"
        phone:
            type: "string"
        adress:
            type: "string"
        arrivedAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        leftAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        room:
            $ref: "#/definitions/Room"
  Guest:
    type: "object"
    description: "Guest-object in querry"
    required:
    - "name"
    - "firstName"
    - "arrivedAt"
    - "leftAt"
    - "room"
    properties:
        firstName:
            type: "string"
            example: "Jane"
        name:
            type: "string"
            example: "Doe"
        mail:
            type: "string"
            pattern: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
            example: "jane.doe@example.com"
        phone:
            type: "string"
        adress:
            type: "string"
        arrivedAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        leftAt:
            type: "string"
            pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
            example: "2020-10-22 04:20"
        room:
            $ref: "#/definitions/RoomIdentifier"
  AlarmQueryObject:
    type: "object"
    required:
    - "type"
    - "sortByName"
    properties:
      type:
        type: "string"
        pattern: /staff|guest/
        example: "guest"
      sortByName:
        type: "boolean"
      firstName:
        type: "string"
      name:
        type: "string"
      arrivedAt:
          type: "string"
          pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
          example: "2020-10-22 04:20"
      leftAt:
          type: "string"
          pattern: /[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) (2[0-3]|[01][0-9]):[0-5][0-9]/
          example: "2020-10-22 04:20"
  SearchObject:
    description: "Subset of attributes to filter the search"
    type: "object"
    required:
    - "sortByName"
    properties:
      sortByName:
        type: "boolean"
    example:
      sortByName: true
      firstName: "Jane"
      name: "Doe"
      arrivedAt: "2020-10-22 04:20"
      leftAt: "2020-10-22 16:20"
  ContactList:
    type: "object"
    properties:
      staffMembers:
        type: "array"
        items:
          $ref: '#/definitions/StaffwId'
      guests:
        type: "array"
        items:
          $ref: '#/definitions/GuestwId'
      
        
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Repository on Github"
  url: "https://github.com/lipilli/CICBO"
